### ISSUE TITLE
Is depth available?

### ISSUE THREAD

**Issue by zhangfuyang** [allenai/ai2thor-rearrangement#11]
Hi, I wonder can we use depth sensor for the rearrangement task? It wasn't mentioned in the paper, but I found there is a DepthRearrangeSensor class in sensors.py. Wondering if this information is available.

Thanks

**Comment by mattdeitke** [comment]
Yes. A depth sensor can be used, as mentioned [here, in the README](https://github.com/allenai/ai2thor-rearrangement#%EF%B8%8F-allowed-observations).

**Comment by Lucaweihs** [comment]
@zhangfuyang Let me know if you need help getting this depth information in practice (it should simply require creating a new experiment config similar to `one_phase_rgb_base.py` where you've added the depth sensor to the [`SENSORS` list](https://github.com/allenai/ai2thor-rearrangement/blob/main/baseline_configs/one_phase/one_phase_rgb_base.py#L15)).

**Comment by zhangfuyang** [comment]
Thanks! I will ping you if I have the problem for getting depth info.
