### ISSUE TITLE
ai2thor.exceptions.UnityCrashException: Unity process has exited

### ISSUE THREAD

**Issue by nnsriram97** [allenai/ai2thor-rearrangement#21]
```
Traceback (most recent call last):
  File “…../allenact/allenact/algorithms/onpolicy_sync/vector_sampled_tasks.py", line 906, in _task_sampling_loop_generator_fn
    current_task = task_sampler.next_task()
  File “…../ai2thor-rearrangement/rearrange/tasks.py", line 1179, in next_task
    raise e
  File “…../ai2thor-rearrangement/rearrange/tasks.py", line 1104, in next_task
    force_axis_aligned_start=self.force_axis_aligned_start,
  File “…../ai2thor-rearrangement/rearrange/environment.py", line 1386, in reset
    task_spec=task_spec, force_axis_aligned_start=force_axis_aligned_start,
  File “…../ai2thor-rearrangement/rearrange/environment.py", line 1319, in _task_spec_reset
    self.controller.reset(self.current_task_spec.scene)
  File “…./lib/python3.7/site-packages/ai2thor/controller.py", line 589, in reset
    self.last_event = self.server.receive()
  File “…../lib/python3.7/site-packages/ai2thor/fifo_server.py", line 170, in receive
    metadata, files = self._recv_message()
  File “…../lib/python3.7/site-packages/ai2thor/fifo_server.py", line 111, in _recv_message
    raise UnityCrashException(message)
ai2thor.exceptions.UnityCrashException: Unity process has exited - check Player.log for errors. Last action message: b'{"action": "Reset", "sceneName": "FloorPlan3_physics", "sequenceId": 0}', returncode=-6
        [vector_sampled_tasks.py: 993]
```

I'm getting UnityCrashException at some point while trying to train a model using allenact for rearrangement one-phase task . Any thoughts on why this occurs or how it can be handled?

**Comment by Lucaweihs** [comment]
Hi @nnsriram97, a few quick questions:

1. Can you remind me how many processes your machine has?
2. Does this error happen immediately at the beginning of training or part way through?

I recall that, on some machines, Unity can have an issue where it will crash in this obtuse way if it runs out of resources (mainly if there are too many open unity processes given the number of processors). Can you try running training with fewer training processes? I'm not sure which training configuration you're using but this is generally done by changing the `def num_train_processes` method.

**Comment by nnsriram97** [comment]
Hi @Lucaweihs, you're right. The training works fine with a fewer number of processes. I tried training with `20,40,80` processes in a 8 GPU server but all of these crashed at different points in the training. Training with `20` processes crashed after 30000 steps and with `80` processes it crashed only after a few iterations. Using num processes < 15 worked fine for me. Thanks!
