### ISSUE TITLE
Could you open-source the data-generation code?

### ISSUE THREAD

**Issue by AaronAnima** [allenai/ai2thor-rearrangement#23]
Hi, I'm really interested in this work, and I want to generate my own rearrange-tasks for research. Currently it seems that the rearrange-tasks can only be loaded from fixed datasets(e.g. train, test, val, combined). Could you open-source the data-generation code? Really appreciate that~

**Comment by Lucaweihs** [comment]
Hi @AaronAnima, 

I've opened a new PR (#24) that adds these data generation scripts. These should be merged soon but if you want to get them even earlier you can find them in the PR.

**Comment by Lucaweihs** [comment]
This is merged now, feel free to reopen this issue (or create a new one) if you have any questions.

**Comment by AaronAnima** [comment]
Thanks! It's really helpful! :)
