### ISSUE TITLE
Dataset contain RGB-D data?

### ISSUE THREAD

**Issue by xuwanyan1998** [allenai/ai2thor-rearrangement#28]
Thanks for holding such a meanningful chanllenge in embodied AI community !
Recently, I was thinking about some new tasks in smart home scenario, and I'm impressed by your brilliant work.
But I also have some problem about your dataset, I mean your challenge is conducted under some Unity virtual scenes, and you said observation allow RGB and depth information,  but I look at your dataset in your .pkl.gz files which include the agent and objects' position and rotation and so on ...So I wonder how could I use the RGB data and depth data to train such a model, or how can I get such a dataset for further research.
That's all !
Thanks a lot !

**Comment by Lucaweihs** [comment]
Hi @xuwanyan1998,

Thanks for your kind words! Our dataset only specifies the start/goal positions of objects and agents. These positions are used by the [AI2-THOR environment](https://ai2thor.allenai.org/) and the depth/RGB images are generated by this environment at inference/training time (they have to be generated at inference time as the agent is allowed to interact with the environment and so there are an unbounded number of possible observations). Have looked at an ran the [`example.py`](https://github.com/allenai/ai2thor-rearrangement/blob/main/example.py) script we include in this repository? It will give you a sense of how you can obtain RGB observations from the environment.

**Comment by xuwanyan1998** [comment]
Hi @Lucaweihs 
Thanks for your reply !
I have not run the _example.py_ yet cause I'm more interested in your dataset, that's my bad. I'll go through the code more carefully next time !
Still, your reply solved my problem !
Thanks a lot !
