### ISSUE TITLE
When I ran the Room Rearrangement task experiment, EOFerror appeared

### ISSUE THREAD

**Issue by twb1235** [allenai/ai2thor-rearrangement#29]
When I run the following command, the error in the screenshot appears。
‘allenact -o rearrange_out -b . baseline_configs/one_phase/one_phase_rgb_resnet_dagger.py ’
The error occurred after the program had been running for some time
There is a GPU on my computer
![image](https://user-images.githubusercontent.com/57714230/147348859-be7d4f60-0b69-47d0-a949-12032b957a28.png)
Please add the following information:
OS: Ubuntu 9.3.0-17ubuntu1~20.04
Allenact: 0.4.o
Allenact-plugins: 0.4.0
GPU： NVIDIA Corporation GP102 [GeForce GTX 1080 Ti]

**Comment by twb1235** [comment]
Hello, I'm sorry to bother you. When I run the code above, I find that all the Thor instances are not running on the GPU. Is this normal? After looking at other people's questions you answered, the above questions may be because all the Thor instances are running on the CPU, resulting in insufficient CPU capacity. Is there any way to solve it。
![捕获1](https://user-images.githubusercontent.com/57714230/147356602-d9b20258-579d-4b94-bcbb-e0a75db4eb13.PNG)

**Comment by Lucaweihs** [comment]
Hi @twb1235,

Sorry, I seem to have missed this issue as it was posted during the Christmas holidays. The THOR instances should definitely be on the GPU. Is it possible that you haven't started an x-server on your GPU? Doing so is required to be able to run AI2-THOR on the GPU. Assuming you're using a recent version of ai2thor and you have X11 installed (`sudo apt install xserver-xorg-core`), you can do so by running:
```bash
sudo ai2thor-xorg start
```

This might complain that it can't find the `ai2thor-xorg` command in which case you can run
```bash
which ai2thor-xorg
```
which should print something like `/your/path/to/ai2thor-xorg`, you should then copy this path and run
```bash
sudo /your/path/to/ai2thor-xorg start
```

**Comment by Lucaweihs** [comment]
Closing this for now but please feel free to reopen if you're still having issues.

**Comment by twb1235** [comment]
> Hi @twb1235,
> 
> Sorry, I seem to have missed this issue as it was posted during the Christmas holidays. The THOR instances should definitely be on the GPU. Is it possible that you haven't started an x-server on your GPU? Doing so is required to be able to run AI2-THOR on the GPU. Assuming you're using a recent version of ai2thor and you have X11 installed (`sudo apt install xserver-xorg-core`), you can do so by running:
> 
> ```shell
> sudo ai2thor-xorg start
> ```
> 
> This might complain that it can't find the `ai2thor-xorg` command in which case you can run
> 
> ```shell
> which ai2thor-xorg
> ```
> 
> which should print something like `/your/path/to/ai2thor-xorg`, you should then copy this path and run
> 
> ```shell
> sudo /your/path/to/ai2thor-xorg start
> ```
Hello, thank you for your reply

Recently, when I was doing one-phase training experiment, I still encountered unitycrashexception, I only started two training processes on one GPU.

At present, only Thor instances are running on the GPU, but it always ends after tens of thousands of steps. Can I put the vectorsampledtask: 0, vectorsampledtask: 1 sampling process on the GPU?

The following figure shows the machine parameters in the configuration file
![机器参数](https://user-images.githubusercontent.com/57714230/159203688-76b2cbbb-81e5-4b6e-945f-f30609196b26.PNG)
